In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    "Name": ["slappy", "boss", "ben", "badass", "aleinx", None],
    "Age": [21,22,23,34,25,np.nan],
    "City": ["pune", "mumbai", "delhi","mumbai", "pune","pune"]

}
print(data)
df = pd.DataFrame(data)
df

{'Name': ['slappy', 'boss', 'ben', 'badass', 'aleinx', None], 'Age': [21, 22, 23, 34, 25, nan], 'City': ['pune', 'mumbai', 'delhi', 'mumbai', 'pune', 'pune']}

     Name   Age    City
0  slappy  21.0    pune
1    boss  22.0  mumbai
2     ben  23.0   delhi
3  badass  34.0  mumbai
4  aleinx  25.0    pune
5    None   NaN    pune

In [ ]:
df.isnull()
df.isnull().sum()

Name    1
Age     1
City    0
dtype: int64

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Name"] = df["Name"].fillna(df["Name"].mode()[0])

df

     Name   Age    City
0  slappy  21.0    pune
1    boss  22.0  mumbai
2     ben  23.0   delhi
3  badass  34.0  mumbai
4  aleinx  25.0    pune
5  aleinx  25.0    pune

In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Salary": [1000,2000,3000,4000,5000,6000],
    "Age": [21,22,23,34,25,np.nan],
    "City": ["pune", "mumbai", "delhi", "mumbai", "pune", "pune"]

})
df

   Salary   Age    City
0    1000  21.0    pune
1    2000  22.0  mumbai
2    3000  23.0   delhi
3    4000  34.0  mumbai
4    5000  25.0    pune
5    6000   NaN    pune

In [ ]:
# fill multiple columns with mean
df[["Age", "Salary"]] = df[["Age", "Salary"]].fillna(df[["Age", "Salary"]].mean())
(df)

   Salary   Age    City
0    1000  21.0    pune
1    2000  22.0  mumbai
2    3000  23.0   delhi
3    4000  34.0  mumbai
4    5000  25.0    pune
5    6000  25.0    pune

In [ ]:
df[["Age", "Salary"]] = df[["Age", "Salary"]].astype(int)
(df)

   Salary  Age    City
0    1000   21    pune
1    2000   22  mumbai
2    3000   23   delhi
3    4000   34  mumbai
4    5000   25    pune
5    6000   25    pune

In [ ]:
df[["Age", "Salary"]] = df[["Age", "Salary"]].apply(lambda x: x * 1.1)
(df)

   Salary   Age    City
0  1100.0  23.1    pune
1  2200.0  24.2  mumbai
2  3300.0  25.3   delhi
3  4400.0  37.4  mumbai
4  5500.0  27.5    pune
5  6600.0  27.5    pune

In [ ]:
#replace specific values
df[["City"]] = df[["City"]].replace("mumbai", "pune")
df

   Salary   Age   City
0  1100.0  23.1   pune
1  2200.0  24.2   pune
2  3300.0  25.3  delhi
3  4400.0  37.4   pune
4  5500.0  27.5   pune
5  6600.0  27.5   pune

ENCODING

In [ ]:
df_encoded = pd.get_dummies(df, columns=["City"])
df_encoded

   Salary   Age  City_delhi  City_pune
0  1100.0  23.1       False       True
1  2200.0  24.2       False       True
2  3300.0  25.3        True      False
3  4400.0  37.4       False       True
4  5500.0  27.5       False       True
5  6600.0  27.5       False       True

In [ ]:
df_no_dup = df.drop_duplicates()
df_no_dup

   Salary   Age   City
0  1100.0  23.1   pune
1  2200.0  24.2   pune
2  3300.0  25.3  delhi
3  4400.0  37.4   pune
4  5500.0  27.5   pune
5  6600.0  27.5   pune

In [ ]:
# Convert all city names to lowercase
df["City"] = df["City"].str.upper()
df2=df.dropna()
#FEMALE female Female FeMale
df2

   Salary   Age   City
0  1100.0  23.1   PUNE
1  2200.0  24.2   PUNE
2  3300.0  25.3  DELHI
3  4400.0  37.4   PUNE
4  5500.0  27.5   PUNE
5  6600.0  27.5   PUNE

In [ ]:
df2.dropna()
df2["Age"] = df2["Age"].astype(int)
df2

   Salary  Age   City
0  1100.0   23   PUNE
1  2200.0   24   PUNE
2  3300.0   25  DELHI
3  4400.0   37   PUNE
4  5500.0   27   PUNE
5  6600.0   27   PUNE

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving rainfall_districtwise_daily_imd.csv to rainfall_districtwise_daily_imd.csv

In [ ]:
# Check uploaded file name
file_name = list(uploaded.keys())[0]
print("Uploaded file:", file_name)

Uploaded file: rainfall_districtwise_daily_imd.csv

In [ ]:
import pandas as pd

df = pd.read_csv("rainfall_districtwise_daily_imd.csv")
df.head()

,State,District,Date,Daily Actual,Daily Normal,Daily Departure Per,Daily Category,Week Date,Weekly \nActual,Weekly Normal,...,Cumulative Date,Cumulative Actual,Cumulative Normal,Cumulative Departue Per,Cumulative \nCategory,Monthly Date,Monthly Acutual,Monthly Normal,Monthly \nDeparture Per,Monthly Category
0,ANDAMAN & NICOBAR,NICOBAR,2026-08-19,0.5,7.4,-94%,LD,13-08-2026 To 19-08-2026,0.5,7.4,...,2026-06-01,431.7,686.9,-37%,D,From 01-08-2026 To 19-08-2026\r,186.1,141.5,31%,E
1,ANDAMAN & NICOBAR,NICOBAR,2026-08-20,0.5,9.4,-94%,LD,13-08-2026 To 19-08-2026,17.5,45.2,...,2026-06-01,432.3,696.3,-38%,D,From 01-08-2026 To 20-08-2026\r,186.6,150.9,24%,E
2,ANDAMAN & NICOBAR,NICOBAR,2026-08-21,2.4,9.9,-76%,LD,13-08-2026 To 19-08-2026,17.5,45.2,...,2026-06-01,431.7,686.9,-37%,D,From 01-08-2026 To 21-08-2026\r,189.0,160.8,18%,N
3,ANDAMAN & NICOBAR,NICOBAR,2026-08-22,9.3,7.1,31%,E,13-08-2026 To 19-08-2026,17.5,45.2,...,2026-06-01,444.0,713.3,-38%,D,From 01-08-2026 To 22-08-2026\r,198.3,167.9,18%,N
4,ANDAMAN & NICOBAR,NICOBAR,2026-08-23,1.3,7.9,-83%,LD,13-08-2026 To 19-08-2026,1.3,7.9,...,2026-06-01,445.3,721.2,-38%,D,From 01-08-2026 To 23-08-2026\r,199.7,175.8,14%,N

In [ ]:
df.head()

df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26915 entries, 0 to 26914
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State                    26915 non-null  object
 1   District                 26915 non-null  object
 2   Date                     26915 non-null  object
 3   Daily Actual             26915 non-null  float64
 4   Daily Normal             26915 non-null  float64
 5   Daily Departure Per      26576 non-null  object
 6   Daily Category           26915 non-null  object
 7   Week Date                26915 non-null  object
 8   Weekly
Actual           26915 non-null  float64
 9   Weekly Normal            26915 non-null  float64
 10  Weekly Departure Per     26653 non-null  object
 11  Weekly Category          26915 non-null  object
 12  Cumulative Date          26915 non-null  object
 13  Cumulative Actual        26915 non-null  float64
 14  Cumulative Normal        26915 non-null  float64
 15  Cumulative Departue Per  26730 non-null  object
 16  Cumulative
Category     26915 non-null  object
 17  Monthly Date             26915 non-null  object
 18  Monthly Acutual          26915 non-null  float64
 19  Monthly Normal           26915 non-null  float64
 20  Monthly
Departure Per   26725 non-null  object
 21  Monthly Category         26915 non-null  object
dtypes: float64(8), object(14)
memory usage: 4.5+ MB

State                        0
District                     0
Date                         0
Daily Actual                 0
Daily Normal                 0
Daily Departure Per        339
Daily Category               0
Week Date                    0
Weekly \nActual              0
Weekly Normal                0
Weekly Departure Per       262
Weekly Category              0
Cumulative Date              0
Cumulative Actual            0
Cumulative Normal            0
Cumulative Departue Per    185
Cumulative \nCategory        0
Monthly Date                 0
Monthly Acutual              0
Monthly Normal               0
Monthly \nDeparture Per    190
Monthly Category             0
dtype: int64

In [ ]:
print(df.columns.tolist())
df.head()

['State', 'District', 'Date', 'Daily Actual', 'Daily Normal', 'Daily Departure Per', 'Daily Category', 'Week Date', 'Weekly \nActual', 'Weekly Normal', 'Weekly Departure Per', 'Weekly Category', 'Cumulative Date', 'Cumulative Actual', 'Cumulative Normal', 'Cumulative Departue Per', 'Cumulative \nCategory', 'Monthly Date', 'Monthly Acutual', 'Monthly Normal', 'Monthly \nDeparture Per', 'Monthly Category']

,State,District,Date,Daily Actual,Daily Normal,Daily Departure Per,Daily Category,Week Date,Weekly \nActual,Weekly Normal,...,Cumulative Date,Cumulative Actual,Cumulative Normal,Cumulative Departue Per,Cumulative \nCategory,Monthly Date,Monthly Acutual,Monthly Normal,Monthly \nDeparture Per,Monthly Category
0,ANDAMAN & NICOBAR,NICOBAR,2026-08-19,0.5,7.4,-94%,LD,13-08-2026 To 19-08-2026,0.5,7.4,...,2026-06-01,431.7,686.9,-37%,D,From 01-08-2026 To 19-08-2026\r,186.1,141.5,31%,E
1,ANDAMAN & NICOBAR,NICOBAR,2026-08-20,0.5,9.4,-94%,LD,13-08-2026 To 19-08-2026,17.5,45.2,...,2026-06-01,432.3,696.3,-38%,D,From 01-08-2026 To 20-08-2026\r,186.6,150.9,24%,E
2,ANDAMAN & NICOBAR,NICOBAR,2026-08-21,2.4,9.9,-76%,LD,13-08-2026 To 19-08-2026,17.5,45.2,...,2026-06-01,431.7,686.9,-37%,D,From 01-08-2026 To 21-08-2026\r,189.0,160.8,18%,N
3,ANDAMAN & NICOBAR,NICOBAR,2026-08-22,9.3,7.1,31%,E,13-08-2026 To 19-08-2026,17.5,45.2,...,2026-06-01,444.0,713.3,-38%,D,From 01-08-2026 To 22-08-2026\r,198.3,167.9,18%,N
4,ANDAMAN & NICOBAR,NICOBAR,2026-08-23,1.3,7.9,-83%,LD,13-08-2026 To 19-08-2026,1.3,7.9,...,2026-06-01,445.3,721.2,-38%,D,From 01-08-2026 To 23-08-2026\r,199.7,175.8,14%,N

In [ ]:
import pandas as pd

df = pd.read_csv("rainfall_districtwise_daily_imd.csv")

print(df.head())
print(df.tail())

               State District        Date  Daily Actual  Daily Normal  \
0  ANDAMAN & NICOBAR  NICOBAR  2026-08-19           0.5           7.4
1  ANDAMAN & NICOBAR  NICOBAR  2026-08-20           0.5           9.4
2  ANDAMAN & NICOBAR  NICOBAR  2026-08-21           2.4           9.9
3  ANDAMAN & NICOBAR  NICOBAR  2026-08-22           9.3           7.1
4  ANDAMAN & NICOBAR  NICOBAR  2026-08-23           1.3           7.9

  Daily Departure Per Daily Category                 Week Date  \
0                -94%             LD  13-08-2026 To 19-08-2026
1                -94%             LD  13-08-2026 To 19-08-2026
2                -76%             LD  13-08-2026 To 19-08-2026
3                 31%              E  13-08-2026 To 19-08-2026
4                -83%             LD  13-08-2026 To 19-08-2026

   Weekly \nActual  Weekly Normal  ... Cumulative Date Cumulative Actual  \
0              0.5            7.4  ...      2026-06-01             431.7
1             17.5           45.2  ...      2026-06-01             432.3
2             17.5           45.2  ...      2026-06-01             431.7
3             17.5           45.2  ...      2026-06-01             444.0
4              1.3            7.9  ...      2026-06-01             445.3

  Cumulative Normal  Cumulative Departue Per  Cumulative \nCategory  \
0             686.9                     -37%                      D
1             696.3                     -38%                      D
2             686.9                     -37%                      D
3             713.3                     -38%                      D
4             721.2                     -38%                      D

                      Monthly Date Monthly Acutual Monthly Normal  \
0  From 01-08-2026 To 19-08-2026\r           186.1          141.5
1  From 01-08-2026 To 20-08-2026\r           186.6          150.9
2  From 01-08-2026 To 21-08-2026\r           189.0          160.8
3  From 01-08-2026 To 22-08-2026\r           198.3          167.9
4  From 01-08-2026 To 23-08-2026\r           199.7          175.8

   Monthly \nDeparture Per  Monthly Category
0                      31%                 E
1                      24%                 E
2                      18%                 N
3                      18%                 N
4                      14%                 N

[5 rows x 22 columns]
             State        District        Date  Daily Actual  Daily Normal  \
26910  WEST BENGAL  UTTAR_DINAJPUR  2026-09-20           0.0           6.3
26911  WEST BENGAL  UTTAR_DINAJPUR  2026-09-21           0.0          14.4
26912  WEST BENGAL  UTTAR_DINAJPUR  2026-09-22           0.0          10.8
26913  WEST BENGAL  UTTAR_DINAJPUR  2026-09-23          16.3           8.3
26914  WEST BENGAL  UTTAR_DINAJPUR  2026-09-24          23.3          10.3

      Daily Departure Per Daily Category                 Week Date  \
26910               -100%             NR  10-09-2026 To 16-09-2026
26911               -100%             NR  10-09-2026 To 16-09-2026
26912               -100%             NR  10-09-2026 To 16-09-2026
26913                 96%             LE  17-09-2026 To 23-09-2026
26914                126%             LE                24-09-2026

       Weekly \nActual  Weekly Normal  ... Cumulative Date Cumulative Actual  \
26910              0.0            6.3  ...      2026-06-01             931.0
26911             45.2           80.9  ...      2026-06-01             931.0
26912             45.2           80.9  ...      2026-06-01             931.0
26913             26.3           77.7  ...      2026-06-01             947.3
26914             23.3           10.3  ...      2026-06-01             970.6

      Cumulative Normal  Cumulative Departue Per  Cumulative \nCategory  \
26910            1358.8                     -31%                      D
26911            1373.2                     -32%                      D
26912            1384.0                     -33%                      D
26913            1392.3                     -32%                      D
26914            1402.6                     -31%                      D

                          Monthly Date Monthly Acutual Monthly Normal  \
26910  From 01-09-2026 To 20-09-2026\r           179.9          213.9
26911  From 01-09-2026 To 21-09-2026\r           179.9          228.3
26912  From 01-09-2026 To 22-09-2026\r           179.9          239.1
26913  From 01-09-2026 To 23-09-2026\r           196.2          247.4
26914  From 01-09-2026 To 24-09-2026\r           219.5          257.7

       Monthly \nDeparture Per  Monthly Category
26910                     -16%                 N
26911                     -21%                 D
26912                     -25%                 D
26913                     -21%                 D
26914                     -15%                 N

[5 rows x 22 columns]

In [ ]:
print("Rows and Columns:", df.shape)

print("\nData Types:")
print(df.dtypes)

Rows and Columns: (26915, 22)

Data Types:
State                       object
District                    object
Date                        object
Daily Actual               float64
Daily Normal               float64
Daily Departure Per         object
Daily Category              object
Week Date                   object
Weekly \nActual            float64
Weekly Normal              float64
Weekly Departure Per        object
Weekly Category             object
Cumulative Date             object
Cumulative Actual          float64
Cumulative Normal          float64
Cumulative Departue Per     object
Cumulative \nCategory       object
Monthly Date                object
Monthly Acutual            float64
Monthly Normal             float64
Monthly \nDeparture Per     object
Monthly Category            object
dtype: object

In [ ]:
print(df.isnull().sum())

State                        0
District                     0
Date                         0
Daily Actual                 0
Daily Normal                 0
Daily Departure Per        339
Daily Category               0
Week Date                    0
Weekly \nActual              0
Weekly Normal                0
Weekly Departure Per       262
Weekly Category              0
Cumulative Date              0
Cumulative Actual            0
Cumulative Normal            0
Cumulative Departue Per    185
Cumulative \nCategory        0
Monthly Date                 0
Monthly Acutual              0
Monthly Normal               0
Monthly \nDeparture Per    190
Monthly Category             0
dtype: int64

In [ ]:
print(df.isnull().sum()[df.isnull().sum() > 0])

Daily Departure Per        339
Weekly Departure Per       262
Cumulative Departue Per    185
Monthly \nDeparture Per    190
dtype: int64

filling missing values

In [ ]:
num_cols = df.select_dtypes(include="number").columns
cat_cols = df.select_dtypes(include="object").columns

In [ ]:
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

In [ ]:
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
print(df.isnull().sum())

State                      0
District                   0
Date                       0
Daily Actual               0
Daily Normal               0
Daily Departure Per        0
Daily Category             0
Week Date                  0
Weekly \nActual            0
Weekly Normal              0
Weekly Departure Per       0
Weekly Category            0
Cumulative Date            0
Cumulative Actual          0
Cumulative Normal          0
Cumulative Departue Per    0
Cumulative \nCategory      0
Monthly Date               0
Monthly Acutual            0
Monthly Normal             0
Monthly \nDeparture Per    0
Monthly Category           0
dtype: int64